services:
  postgres:
    image: postgres:17
    container_name: energy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: energy_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: energy_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build:
      context: ./backend
    container_name: energy_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energy_analytics
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MQTT_BROKER_URL: tcp://mosquitto:1883
      MQTT_TOPIC: shellyemg3-e4b323227cfc/#
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
    container_name: energy_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: